<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RechercheStageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recherche_stages')->insert([
            [
                'dateCreation' => '2025-01-10',
                'dateModification' => '2025-01-20',
                'date1erContact' => '2025-01-10',
                'typeContact' => 'Mail',
                'nomContact' => 'Dupont',
                'prenomContact' => 'Jean',
                'fonctionContact' => 'Responsable RH',
                'telephoneContact' => '0601020304',
                'adresseMailContact' => 'jean.dupont@example.com',
                'observations' => 'Contact très réactif.',
                'dateRelance' => null,
                'statut' => 'En cours',
                'idUPPA' => '611082',
                'idEntreprise' => 1,
            ],
            [
                'dateCreation' => '2025-01-10',
                'dateModification' => '2025-01-20',
                'date1erContact' => '2025-01-10',
                'typeContact' => 'Téléphone',
                'nomContact' => 'Martin',
                'prenomContact' => 'Claire',
                'fonctionContact' => 'Directrice Commerciale',
                'telephoneContact' => '0612345678',
                'adresseMailContact' => 'claire.martin@example.com',
                'observations' => 'Préfère être contactée par téléphone.',
                'dateRelance' => '2025-01-20',
                'statut' => 'Relancé',
                'idUPPA' => '611082',
                'idEntreprise' => 2,
            ],
            [
                'dateCreation' => '2025-01-11',
                'dateModification' => '2025-01-17',
                'date1erContact' => '2025-01-10',
                'typeContact' => 'Présentiel',
                'nomContact' => 'Bernard',
                'prenomContact' => 'Louis',
                'fonctionContact' => 'Chef de Projet',
                'telephoneContact' => '0623456789',
                'adresseMailContact' => 'louis.bernard@example.com',
                'observations' => 'Discussion productive lors de la réunion.',
                'dateRelance' => null,
                'statut' => 'Validé',
                'idUPPA' => '611082',
                'idEntreprise' => 3,
            ],
            [
                'dateCreation' => '2025-01-12',
                'dateModification' => '2025-01-12',
                'date1erContact' => '2025-01-12',
                'typeContact' => 'Mail',
                'nomContact' => 'Lemoine',
                'prenomContact' => 'Alice',
                'fonctionContact' => 'Responsable Marketing',
                'telephoneContact' => '0634567890',
                'adresseMailContact' => 'alice.lemoine@example.com',
                'observations' => 'En attente de retour.',
                'dateRelance' => null,
                'statut' => 'En cours',
                'idUPPA' => '611000',
                'idEntreprise' => 4,
            ],
            [
                'dateCreation' => '2025-01-12',
                'dateModification' => '2025-01-14',
                'date1erContact' => '2025-01-12',
                'typeContact' => 'Téléphone',
                'nomContact' => 'Garnier',
                'prenomContact' => 'Paul',
                'fonctionContact' => 'Ingénieur Logiciel',
                'telephoneContact' => '0645678901',
                'adresseMailContact' => 'paul.garnier@example.com',
                'observations' => 'A proposé une collaboration.',
                'dateRelance' => '2025-01-13',
                'statut' => 'Validé',
                'idUPPA' => '611000',
                'idEntreprise' => 1,
            ],
            [
                'dateCreation' => '2025-01-03',
                'dateModification' => '2025-01-12',
                'date1erContact' => '2025-01-03',
                'typeContact' => 'Courrier',
                'nomContact' => 'Moreau',
                'prenomContact' => 'Elodie',
                'fonctionContact' => 'Chargée de Communication',
                'telephoneContact' => '0656789012',
                'adresseMailContact' => 'elodie.moreau@example.com',
                'observations' => 'En attente de décision.',
                'dateRelance' => null,
                'statut' => 'En cours',
                'idUPPA' => '613453',
                'idEntreprise' => 6,
            ],
            [
                'dateCreation' => '2025-01-13',
                'dateModification' => '2025-01-17',
                'date1erContact' => '2025-01-13',
                'typeContact' => 'Présentiel',
                'nomContact' => 'Roux',
                'prenomContact' => 'Thomas',
                'fonctionContact' => 'Analyste Financier',
                'telephoneContact' => '0667890123',
                'adresseMailContact' => 'thomas.roux@example.com',
                'observations' => 'Souhaite un suivi mensuel.',
                'dateRelance' => '2025-01-17',
                'statut' => 'Relancé',
                'idUPPA' => '613453',
                'idEntreprise' => 7,
            ],
            [
                'dateCreation' => '2025-01-01',
                'dateModification' => '2025-01-02',
                'date1erContact' => '2025-01-01',
                'typeContact' => 'Mail',
                'nomContact' => 'Durand',
                'prenomContact' => 'Sophie',
                'fonctionContact' => 'Consultante',
                'telephoneContact' => '0678901234',
                'adresseMailContact' => 'sophie.durand@example.com',
                'observations' => 'Intéressée par le projet.',
                'dateRelance' => null,
                'statut' => 'Refusé',
                'idUPPA' => '613453',
                'idEntreprise' => 3,
            ],
            [
                'dateCreation' => '2025-01-08',
                'dateModification' => '2025-01-14',
                'date1erContact' => '2025-01-07',
                'typeContact' => 'Téléphone',
                'nomContact' => 'Blanc',
                'prenomContact' => 'Julie',
                'fonctionContact' => 'Responsable IT',
                'telephoneContact' => '0689012345',
                'adresseMailContact' => 'julie.blanc@example.com',
                'observations' => 'Demande des précisions supplémentaires.',
                'dateRelance' => '2025-01-14',
                'statut' => 'En cours',
                'idUPPA' => '610123',
                'idEntreprise' => 7,
            ],
            [
                'dateCreation' => '2025-01-12',
                'dateModification' => '2025-01-13',
                'date1erContact' => '2025-01-12',
                'typeContact' => 'Courrier',
                'nomContact' => 'Noir',
                'prenomContact' => 'Hugo',
                'fonctionContact' => 'Développeur',
                'telephoneContact' => '0690123456',
                'adresseMailContact' => 'hugo.noir@example.com',
                'observations' => 'Disponible uniquement les après-midis.',
                'dateRelance' => null,
                'statut' => 'Refusé',
                'idUPPA' => '610123',
                'idEntreprise' => 5,
            ],
        ]);
    }
}
