name: Test Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_test
          MYSQL_USER: test_github
          MYSQL_PASSWORD: test_github
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo, pdo_mysql, xdebug
          tools: composer:v2

      - name: Debug path
        run: |
          pwd
          ls -la

      - name: Update dependencies
        run: |
          cd DOCKER/php/laravel/suivi-stage
          composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env.example to .env.ci
        run: |
          cd DOCKER/php/laravel/suivi-stage
          cp .env.example .env.ci
          echo "DB_CONNECTION=mysql" >> .env.ci
          echo "DB_HOST=mysql" >> .env.ci
          echo "DB_PORT=3306" >> .env.ci
          echo "DB_DATABASE=test_db" >> .env.ci
          echo "DB_USERNAME=test_user" >> .env.ci
          echo "DB_PASSWORD=test_password" >> .env.ci

      - name: Run migrations
        run: |
          cd DOCKER/php/laravel/suivi-stage
          php artisan migrate:fresh --seed

      - name: Run tests
        run: |
          cd DOCKER/php/laravel/suivi-stage
          ./vendor/bin/phpunit --coverage-html ./tests/coverage

      - name: Upload coverage as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tests/coverage